version: '3'
services:
  plugin:
    build:
      context: .
    volumes:
      - .:/app
    links:
      - app
      - db
    environment:
      DATABASE_URL: postgres://postgres@db/postgres?sslmode=disable
      API_KEY: changeme
      MASTER_KEY: secret
      APP_NAME: kotlin
      ASSET_STORE: fs
      ASSET_STORE_URL_PREFIX: http://localhost:3000/files
      ASSET_STORE_SECRET: asset-secret
      PUBSUB_URL: ws://app:3000/pubsub
      SKYGEAR_ADDRESS: tcp://app:5555
      SKYGEAR_ENDPOINT: http://app:3000
    ports:
      - "9001:9000"
  db:
    image: mdillon/postgis:9.5
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  app:
    image: quay.io/skygeario/skygear-server:latest
    ports:
      - "3000:3000"
    volumes:
      - app_data:/app/data
    links:
      - db
    command: skygear-server --http
    environment:
      DATABASE_URL: postgresql://postgres:@db/postgres?sslmode=disable
      API_KEY: changeme
      MASTER_KEY: secret
      APP_NAME: _
      TOKEN_STORE: jwt
      TOKEN_STORE_SECRET: jwt_secret
      ASSET_STORE: fs
      ASSET_STORE_URL_PREFIX: http://localhost:3000/files
      ASSET_STORE_SECRET: asset-secret
      PLUGINS: KOTLIN
      KOTLIN_TRANSPORT: http
      KOTLIN_PATH: http://plugin:9000
    

volumes:
  db_data:
    driver: local
  app_data:
    driver: local
